### PR TITLE
Bunch of Improvements & Updates

### PR DESCRIPTION
**Pull request by jsetton**
I made a bunch of improvements and updates including adding support for color temperature, scene and entertainment (channel, input & speaker) controllers. I also added drastically improved the test suite. This is a definitely a big update so let me know if you want me to split the changes.

**Highlights**

- **Alexa Response State Accuracy Improvement**
  - OH state is now reported back in most Alexa responses including state properties, instead of the state included in the original request.

- **Mocha Testing Improvement**
  - Improved the test suite for this project and tried to organized it so that it is easy to add/read test cases.
  - Included v2/v3 test cases for most implemented functionalities

- **Color Temperature Support**
  - Implemented support for dimmer items to work with hue + lifx (default) and number items for custom integration using the color temperature value

- **Entertainment Controller Support**
  - Added ability to define default speaker volume increment through tag parameter

- **Scene Trigger Support**
  - Added supportsDeactivation parameter support (enabled by default)

- **Thermostat Mode Binding Tag Parameter Support**
  - Added ability to define through tag parameter the binding used in OH (ecobee, nest & zwave bindings currently only defined). The user mapping ability will work in parallel with the latter having precedence.

### CODE REVIEW

**Comment by digitaldan** [comment]
Thank you such much for the PR. Really appreciate the help.  Yes the PR is big, but since this is in such an early state of the code, I'm fine with it.  The tests are especially awesome.  Once you fix the conflict from the last PR, I will go ahead and merge your changes and test from there.  One thing I have not even tried testing is if v2 compatibility still works.  Amazon's guide says to need to support both for some amount of time as users get migrated to the v3 endpoint (like 24 hours maybe) 

And wow did i copy and past "category" misspelled a lot!

**Comment by digitaldan** [comment]
@jsetton can you fix the conflicts and @fmeies can you add any final comments?  I would like to merge this and move the v3 branch over to the official repo for us to work against

**Comment by fmeies** [comment]
I reviewed @jsetton 's changes to the test structure. Looks good, thank you!

**Comment by jsetton** [comment]
@digitaldan based on your comments, I am working to fix the v2 compatibility as well since my changes broke it. I am also planning to add v2 test cases. Hopefully, I can update this PR by the end of today if not tomorrow.

**Comment by digitaldan** [comment]
👍

**Comment by jsetton** [comment]
@fmeies I have implemented ohConnectorV2 test support and split v2/v3 test case files into their own folders. Let me know if this looks good to you.

24a6c7e5e3948c1d52e911a8251752c3811c501a

@digitaldan I have fixed v2 compatibility and made some minor improvement in the process. You should be all set once @fmeies gives the green light on the changes I made with the testing framework.

**Comment by fmeies** [comment]
Good idea to add v2 tests and separate them from v3, PR looks good to me. Although I did not have the opportunity to test the code in my setup. Anyway, let's move over 👍

**Comment by digitaldan** [comment]
Awesome, I will have a look tonight.  Just FYI, I am going to hookup travis-ci today or tomorrow so we can start automating the tests.  I'm also going to use this to deploy updates to our production lambda endpoints once we get to v3 .

**Comment by jsetton** [comment]
@digitaldan I noticed you enabled travis build. So I added the travis configuration and made a few changes to allow the test to run with some default settings as config.js is not available in the repository. Let me know if these work for you.

**Comment by digitaldan** [comment]
@jsetton your timing is uncanny :-) Awesome, I will integrate your travis file with mine!

**Comment by jsetton** [comment]
For reference purpose, this is the test case config format I implemented:

**Controller v2/v3**
```
module.exports = [
  {
    description: "<test case description>",
    directive: <alexa directive>,
    mocked: {
      openhab: <openhab mock response(s)>,
      staged: <set to true if multiple mocked responses with different values>
    },
    expected: {
      alexa: <alexa expected result>
      openhab: <openhab expected command(s)>
    }
  }
];
````

**Discover v2**
```
module.exports = {
  description: "<test case description>",
  mocked: <openhab mock response>,
  expected: {
    "<item name #1>": {
      "actions": [
        "<action #1>",
        "<action #2>",
        "...",
      ],
      "applianceTypes": ["<type #1>", "..."]
      "additionalApplianceDetails": { 
        <detail #1>,
        ...
      }
    },
    ...
  }
};
```

**Discover v3**
```
module.exports = {
  description: "<test case description>",
  mocked: <openhab mock response>,
  expected: {
    "<item name #1>": {
      "capabilities": [
        "<namespace #1>",
        "<namespace #2>",
        "...",
      ],
      "displayCategories": ["<category #1>", "..."]
      "parameters": { # For non-standard property validation
        "Alexa.<interface name>.<property name>": "<property value>",
        ...
      },
      "propertyMap": {
        <property #1>,
        ....
      }
    },
    ...
  }
};
```

**Comment by digitaldan** [comment]
Lets move our development over to https://github.com/openhab/openhab-alexa/tree/v3 , thanks!

**Pull request merged**
