### PR TITLE
Fixed Auth

### PR DESCRIPTION
**Pull request by Clifford-Foster**
Included the ability to respond to Authorization requests.  This is necessary when linking accounts from the Alexa Skill.

### CODE REVIEW

**Comment by digitaldan** [comment]
Hi Clifford, i was not fully aware of this call as account linking works fine already.  According to https://developer.amazon.com/docs/device-apis/alexa-authorization.html this is needed to send events to the Alexa event gateway, are you planning on implementing something like this?

**Comment by Clifford-Foster** [comment]
Hi Dan, the account linking wasn't working for me when I implemented it for Australia (in development).  

When I tracked it down I noticed that the reply didn't have a header as specified in  [https://developer.amazon.com/docs/device-apis/alexa-authorization.html](url) .   Once I implemented this the Account Linking worked perfectly.

My next challenges are:
(1) I am linking to my own OpenHAB cloud.   Currently the url is stored in the .env file.  Have you found a way to make this available in a user entered field/setting?   I can't find a way to do this.
(2) I have to used basic authentication to my OpenHAB cloud.   Where do I stored the secrets so that I can use oauth between the skill and OpenHAB cloud?   This will save me tracing through all your code.

Btw - great work on the Skill.  I look forward to contributing.

**Comment by Clifford-Foster** [comment]
Also, apologies but there is a missing closing '}' in that.  I did a quick clean on the code as it had lots of log statements.  I'll fix when I get home tonight.

**Comment by Clifford-Foster** [comment]
Updated with missing
```
  context.succeed(result);
}
```

**Comment by jsetton** [comment]
@Clifford-Foster I just brought up that [topic](https://github.com/openhab/openhab-alexa/issues/73) in the main project. Did you enable the "Send Alexa Events" permission on your skill? That would explain why you needed the skill to respond to Alexa.Authorization directives since the skill cannot be enabled at the user level if no successful response is sent back. But, from my understanding, this scenario only happens when that permission is enabled.

image

**Comment by Clifford-Foster** [comment]
@jsetton that's exactly what I did ... without thinking through the implications :)  Thanks for solving the mystery.

**Pull request closed without merging**
